image: quay.io/tike/alpine-oc-node

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  PROJECT_NAME: "imitaatiopeli-azure-service"
  PROJECT_VERSION: "1.0.0"

stages:
  - setup
  - test
  - dependency-track-generate
  - dependency-track-submit
  - deploy

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

# Define the process for setup stage
build:
  stage: setup
  image: node:22-alpine
  tags:
    - ohtu-build-4
  script:
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules

# Define the process for test stage
test:
  stage: test
  image: node:22-alpine
  tags:
    - ohtu-build-4
  script:
    - npm run coverage
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    name: imitaatiopeli-coverage
    paths:
      - coverage
    expire_in: 1 hour
  extends: .dependencies_cache

generate-sbom:
  stage: dependency-track-generate
  image: node:22-alpine
  only:
    - schedules
  tags:
    - ohtu-build-4
  script:
    - npm ci
    - npx @cyclonedx/cyclonedx-npm --output-file sbom.xml
  artifacts:
    expire_in: 1h
    paths:
      - sbom.xml

submit-sbom:
  image: alpine:latest
  stage: dependency-track-submit
  only:
    - schedules
  tags:
    - ohtu-build-4
  dependencies:
    - generate-sbom
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST ${DTRACK_API_URL} -H 'Content-Type: multipart/form-data' -H 'X-Api-Key: '${DTRACK_API_KEY} -F 'projectName='${PROJECT_NAME} -F 'autoCreate=true' -F 'projectVersion='${PROJECT_VERSION} -F 'bom=@sbom.xml'"

deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-4
  environment:
    name: development
  only:
    - main
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project imitaatiopeli
    # create application if it does not exist
    - |
      if oc get deploy/imitaatiopeli-azure-dev; then 
        echo "The application already exists."
      else 
        oc new-app . --name=imitaatiopeli-azure-dev --strategy=docker
        echo "The application has been created."
      fi
    # add secrets here
    # list environment variables here
    - oc set env deploy/imitaatiopeli-azure-dev AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
    - oc set env deploy/imitaatiopeli-azure-dev AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
    - oc set env deploy/imitaatiopeli-azure-dev AZURE_OPENAI_DEPLOYMENT_NAME=$AZURE_OPENAI_DEPLOYMENT_NAME
    - oc set env deploy/imitaatiopeli-azure-dev AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
    - oc set env deploy/imitaatiopeli-azure-dev DB_HOST=$DB_HOST_DEV
    # postgres environment variables
    - oc set env deploy/imitaatiopeli-azure-dev OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/imitaatiopeli-azure-dev OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/imitaatiopeli-azure-dev TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build imitaatiopeli-azure-dev --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/imitaatiopeli-azure-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/imitaatiopeli-azure-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_test:
  stage: deploy
  tags:
    - ohtu-build-4
  environment:
    name: test
  only:
    - test
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project imitaatiopeli
    # create application if it does not exist
    - |
      if oc get deploy/imitaatiopeli-azure-test; then 
        echo "The application already exists."
      else 
        oc new-app . --name=imitaatiopeli-azure-test --strategy=docker
        echo "The application has been created."
      fi
    # add secrets here
    # list environment variables here
    - oc set env deploy/imitaatiopeli-azure-test AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
    - oc set env deploy/imitaatiopeli-azure-test AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
    - oc set env deploy/imitaatiopeli-azure-test AZURE_OPENAI_DEPLOYMENT_NAME=$AZURE_OPENAI_DEPLOYMENT_NAME
    - oc set env deploy/imitaatiopeli-azure-test AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
    - oc set env deploy/imitaatiopeli-azure-test DB_HOST=$DB_HOST_TEST
    # postgres environment variables
    - oc set env deploy/imitaatiopeli-azure-test OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/imitaatiopeli-azure-test OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/imitaatiopeli-azure-test TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build imitaatiopeli-azure-test --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/imitaatiopeli-azure-test --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/imitaatiopeli-azure-test --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-4
  environment:
    name: prod
  only:
    - prod
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD
    - oc project imitaatiopeli
    # create application if it does not exist
    - |
      if oc get deploy/imitaatiopeli-azure-prod; then 
        echo "The application already exists."
      else 
        oc new-app . --name=imitaatiopeli-azure-prod --strategy=docker
        echo "The application has been created."
      fi
    # add secrets here
    # list environment variables here
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_DEPLOYMENT_NAME=$AZURE_OPENAI_DEPLOYMENT_NAME
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
    - oc set env deploy/imitaatiopeli-azure-prod DB_HOST=$DB_HOST_PROD
    # postgres environment variables
    - oc set env deploy/imitaatiopeli-azure-prod OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/imitaatiopeli-azure-prod OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/imitaatiopeli-azure-prod TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build imitaatiopeli-azure-prod --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/imitaatiopeli-azure-prod --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/imitaatiopeli-azure-prod --patch '{"spec":{"failedBuildsHistoryLimit":1}}'

deploy_prod_periodically:
  stage: deploy
  tags:
    - ohtu-build-4
  environment:
    name: prod
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "prod"'
      when: always
    - when: never
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD
    - oc project imitaatiopeli
    # create application if it does not exist
    - |
      if oc get deploy/imitaatiopeli-azure-prod; then 
        echo "The application already exists."
      else 
        oc new-app . --name=imitaatiopeli-azure-prod --strategy=docker
        echo "The application has been created."
      fi
    # add secrets here
    # list environment variables here
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_DEPLOYMENT_NAME=$AZURE_OPENAI_DEPLOYMENT_NAME
    - oc set env deploy/imitaatiopeli-azure-prod AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
    - oc set env deploy/imitaatiopeli-azure-prod DB_HOST=$DB_HOST_PROD
    # postgres environment variables
    - oc set env deploy/imitaatiopeli-azure-prod OPENSHIFT_NODEJS_IP=$OPENSHIFT_NODEJS_IP
    - oc set env deploy/imitaatiopeli-azure-prod OPENSHIFT_NODEJS_PORT=$OPENSHIFT_NODEJS_PORT
    - oc set env deploy/imitaatiopeli-azure-prod TZ="Europe/Helsinki"
    # start build process in OpenShift
    - oc start-build imitaatiopeli-azure-prod --from-dir=. --follow
    # patch openshift buildConfig file
    - oc patch bc/imitaatiopeli-azure-prod --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/imitaatiopeli-azure-prod --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
